### ISSUE TITLE
When to fire up badge workers?

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#11]
Currently letting the app sleep for 5s before running the BadgeWorkers for the first time, in order to give the DependencyWorkers a chance to catch up. That applies to the "first run" of the Workers. On the scheduler run, the BadgeWorkers are just planned 5 minutes later than the Dependency Workers. @bartkamphorst in #4:

> Either the badge workers should wait for data to be stored (either by polling the store every so often, or, preferably, through some kind of callback), or the badge job should be scheduled/fired up by the dependency workers.

Sounds like a good idea! But, in the latter case: if a DependencyWorker throws an unhandled exception, that would mean the Badge Worker also doesn't get called (and so the SVG would remain the same as before the DepWorker threw the exception). Should we handle this by just catching all exceptions in DepWorker#perform and setting dependencies to `nil` in that case?

On the first run, just waiting for the store to fill up is a possibility, although in that case, if the DepWorkers run into a problem, the app wouldn't start forever.

**Comment by bartkamphorst** [comment]
Rather than waiting for the store to fill up, I'm now thinking there should be a separate Queue set up for the workers to communicate. That way, the BadgeWorkers just check for work in the Queue, and sleep if there is nothing to do (and perhaps exit after some time since they will be fired up again later by the scheduler). 

> if a DependencyWorker throws an unhandled exception, that would mean the Badge Worker also doesn't get called

This doesn't need to happen. If the DependencyWorker has an `ensure` clause, it can fail to parse the file, and still leave a message in the Queue for the BadgeWorker to create a badge for that project that indicates problems.

**Comment by dometto** [comment]
A queue may already exist: https://github.com/brandonhilkert/sucker_punch/blob/master/lib/sucker_punch/queue.rb

**Comment by dometto** [comment]
> Rather than waiting for the store to fill up, I'm now thinking there should be a separate Queue set up for the workers to communicate.

Do you have an idea of what this would look like? Is a Queue just some global (?) object that both DependencyWorkers and BadgeWorkers can access? Or is it e.g. a separate Moneta store?

This still leaves the problem of what to do on the initial run; we have to wait for the Queue to be filled up, but how do we know it's completely filled?

This would be easier if we spin up BadgeWorkers from DependencyWorkers, as was your initial suggestion. What disadvantages does that have?

**Comment by bartkamphorst** [comment]
> Is a Queue just some global (?) object that both DependencyWorkers and BadgeWorkers can access?

It doesn't have to be a global variable, but yes, all workers would be given access to it. `q = Queue.new` and then pass `q` to the workers on initialization.

**Comment by bartkamphorst** [comment]
> we have to wait for the Queue to be filled up, but how do we know it's completely filled?

Remind me why it needs to be completely filled? Because `Queue#pop` "blocks," which means that the process calling `q.pop` on an empty queue will wait (/sleep) until something has been added to the queue and `q.pop` returns something.

**Comment by dometto** [comment]
> Remind me why it needs to be completely filled?

Ah, so the idea is there is a continual loop that checks for work for the duration of the program?

> all workers would be given access to it. q = Queue.new and then pass q to the workers on initialization.

Two questions:

* do we need a special Queue class for this, or might we just as well use a Hash or Array?
* any thread-safety concerns due to the fact that multiple threads can modify this variable in the main thread?

Think I'm seeing the approach though. Any reasons to prefer this to the current approach in https://github.com/repotag/cutting_edge/pull/28?

**Comment by bartkamphorst** [comment]
> Ah, so the idea is there is a continual loop that checks for work for the duration of the program?

Yes and no. Yes, as long as the queue contains tasks, workers keep coming back to the queue (`queue.pop`) to see if there is more work to be done, but once the queue is empty, `queue.pop` blocks, and the worker will wait until something new is added to the queue. In that sense there is no continual loop, as the workers won't keep polling the queue every second or so.

> do we need a special Queue class for this, or might we just as well use a Hash or Array?

Yes, [this one](https://ruby-doc.org/core-2.5.0/Queue.html). Hashes or Arrays are non-blocking, so they will simply return `nil` if the queue is empty. See [here](https://www.rubyguides.com/2019/10/ruby-queues/) for an introduction.

> any thread-safety concerns due to the fact that multiple threads can modify this variable in the main thread?

Queues themselves are thread-safe, but whether the resulting application is depends also on what you put into the queue of course.

**Comment by dometto** [comment]
Thanks, that introduction cleared things up. Then I'm thinking we have the following threads:

* Main thread (Sinatra app)
* One thread in which we run rufus-scheduler
  * from that thread, the DependencyWorkers fire up (these need to be run periodically, to check if any dependencies have a new version)
  * the DependencyWorkers add jobs to the Queue
* Then we have X+Y threads, where X is the amount of BadgeWorkers we want, and Y is the amount of EMailWorkers we want, and they keep checking the Queue?

Does that make sense?

**Comment by bartkamphorst** [comment]
Yes that makes sense! With the small remark that I would say that the BadgeWorkers and EMailWorkers would track the state of the cue, not "keep checking" the queue (which implies pollling). Would this work with heroku or would heroku kill off the X BadgeWorkers and Y EMailWorkers if they are idle?

**Comment by dometto** [comment]
> I would say that the BadgeWorkers and EMailWorkers would track the state of the cue, not "keep checking" the queue (which implies pollling)

Can you say more what this means concretely? Sorry, haven't really mastered the concept yet!

> Would this work with heroku or would heroku kill off the X BadgeWorkers and Y EMailWorkers if they are idle?

Good question. The rufus-scheduler thread is not killed (even though I suppose it's just there checking the time in the background), so maybe it's ok!

**Comment by bartkamphorst** [comment]
> Can you say more what this means concretely? Sorry, haven't really mastered the concept yet!

I just mean that the Workers are **not** doing the following:
```ruby
while true
  if x = queue.pop
    # do work
  else
    sleep 1
  end
  # and try again
end
```

Computationally this would mean a lot of useless overhead since the queue may be empty for hours on end, and you would have X+Y workers calling `queue.pop` and going back to sleep every second. However, since there is already an object that "knows" what the state of the queue is (empty or not), namely the queue itself, you can do something like the following:

```ruby
while queue.pop
  # do work
end
```

Since `queue.pop` is "blocking," the worker will simply wait for the queue object to return a value, which it will only do when a) there is something in the queue, and b) it is this worker's turn to get a value. For comparison, consider:

```ruby
while queue.pop(true)
  # do work
end
```

or the Array-equivalent:
```ruby
arr = ['a', 'b', 'c']
while arr.pop
  # do work
end
```

Both of these will at some point return `nil` and the loop will thus terminate (and the workers would terminate as a result as well).

**Comment by dometto** [comment]
I see! I guess that means we have different Queues for BadgeWorkers and MailWorkers!

**Comment by dometto** [comment]
@bartkamphorst I'm not sure now about how to make SuckerPunch play well with the approach outlined in this issue, and whether that's possible. [Here](https://github.com/brandonhilkert/sucker_punch#usage) it says each SuckerPunch job 'acts as its own queue'. And:

> Each job is setup as a pool, which equates to its own queue with individual workers working against the jobs.

Any thoughts?

**Comment by bartkamphorst** [comment]
Best way forward I think is just to fire off a BadgeJob and a MailJob at the end of the DependencyJob. 👍

**Comment by dometto** [comment]
Ok, that's being done in #28 !

**Comment by bartkamphorst** [comment]
Excellent. Sorry for adding to the confusion.

**Comment by dometto** [comment]
No worries, you were right this is the best design pattern, but SuckerPunch/our goal of getting the app to work on heroku limit our options.
