### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#13]
- [x] Pick a name and add namespaces
- [x] Get code coverage up to par
- [x] Repo configuration in separate YAML file
- [x] Allow setting a `config.rb` for options
- [x] Add CLI options to `bin/cutting_edge` (port, binding address, etc.)
- [x] Add Rakefile with release tools (from `gollum`?)
- [x] Add a gemspec, move dependencies there with sane version requirements
- [x] Write docs
- [x] Provide example Heroku `Procfile`
- [x] Build/Release

**Comment by bartkamphorst** [comment]
Here's a couple of suggestions for names:
* dependentiam
* gemin (pronounce: jamming)
* gemalyze
* congemparary
* cutting_edge
* neoteric

**Comment by dometto** [comment]
Quite like gemalyze and cutting_edge! (cutting_badge? ;))

**Comment by dometto** [comment]
cutting_edge it is. :) Namespace `CuttingEdge::`?

**Comment by bartkamphorst** [comment]
Yup!

**Comment by dometto** [comment]
What would be a good name for the launcher script (which will be available on `$PATH` after a `gem install`)? `edge`? `cutting_edge`? `cutting-edge`?

**Comment by dometto** [comment]
Done a first `v0.0.1` release to register the gem. First full release should be e.g. 0.1, or 0.5?

> What would be a good name for the launcher script (which will be available on $PATH after a gem install)? edge? cutting_edge? cutting-edge?

Settled on cutting_edge

**Comment by bartkamphorst** [comment]
> First full release should be e.g. 0.1, or 0.5?

0.1 seems like a good place to start!
