### ISSUE TITLE
Improve SVG styling

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#14]
See discussion in #1

**Comment by dometto** [comment]
Question: do we want the total 'badness' of the dependency status to take account of the difference between outdated_major, _minor, and _bump -- e.g. to determine the badge color with?  For instance: 

* Badge goes red when there's an outdated_major
* Badge goes orange when there's an outdated_minor
* Badge goes yellow when there's an outdated_bump

...and we could make the shade of red/orange/yellow depend on either the total number or the percentage of dependencies of that sort that are broken?

That would mean that if a gem has only one outdated_major, but lots of outdated_minors, the color would be a not-too-worrying red. Does that make sense, or should we treat outdated_minors the same as outdated_majors?

**Comment by bartkamphorst** [comment]
Alternatively, the badge could show circles of a certain color for each type of problem with the number of problems embedded in each circle. So, for example, (4) (2) (0) (0) (5) in colors red, orange, yellow, grey, green, respectively (I don't know how to visualize this quickly).

**Comment by dometto** [comment]
Yes, that's also a possibility! Would it be clear enough what those mean for the casual onlooker, you think?

**Comment by bartkamphorst** [comment]
If we set the title attribute of the svg intelligently, people can get more information in the tooltip.

**Comment by bartkamphorst** [comment]
Something like this?

![test](https://user-images.githubusercontent.com/571173/74584358-b912d600-4fd1-11ea-800f-712dcb5ab479.jpg)

**Comment by dometto** [comment]
Could [these templates](https://github.com/badges/shields/tree/master/gh-badges/templates) be useful?

**Comment by dometto** [comment]
If it's easier, the numbers wouldn't necessarily have to be embedded in circles, but we could just have their piece of the background have different colors?

> If we set the title attribute of the svg intelligently, people can get more information in the tooltip.

We can do this from within the svg source? That's cool! Then another fallback option could be to simply have the badge show 'Outdated', 'Ok', or 'Unknown', and have the info on the numbers in the tooltip?

**Comment by bartkamphorst** [comment]
Well, `victor` allows you to set any svg attribute, including title. So we can simply use the data to generate an appropriate title for each badge we create.

**Comment by dometto** [comment]
Cool, I didn't know SVGs worked that way! I mean, if you have a normal embedded image, you'd set the alt text in the tag that includes it: `<img href="http://somewhere.else/image.png alt="blah" />`. But if we can set the title in the SVG, maybe the easier way of going would be to have simpler badges, and provide the info in the title? Unless you think you can get the fancy graphics working of course!
