### ISSUE TITLE
Mock HTTP calls in specs

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#17]
Getting this error on Travis, but not locally:
```
     Failure/Error: logger.error(message) if ::RubyDeps.enable_logging
```
A bit puzzled as this happens in `spec_helper.rb`:
```ruby
load File.expand_path('../../lib/app.rb', __FILE__)
RubyDeps.set(:enable_logging, false)
```
Have fixed it temporarily by adding `defined?(::RubyDeps)` condition to the logger methods.

Additionally, I just noticed that the spec files are themselves being covered by simplecov:

<img width="454" alt="Screenshot 2020-02-17 at 18 19 23" src="https://user-images.githubusercontent.com/147111/74674640-1feee580-51b2-11ea-8ae0-dd47f62857eb.png">

Seems like the RSpec environment is being set up quite right, but don't know what the issue is. 😕

**Comment by dometto** [comment]
Also, the specs are now actually doing HTTP queries. Does that make sense, or should we mock those?

**Comment by bartkamphorst** [comment]
> the specs are now actually doing HTTP queries

Those should be mocked for sure.

**Comment by bartkamphorst** [comment]
The issues with SimpleCov should be fixable by adding a `.simplecov` config file, and perhaps explicitly adding filters to exclude `_spec.rb` files. See https://github.com/colszowka/simplecov/issues/340 .

**Comment by dometto** [comment]
Thanks for the pointer! SimpleCov now working locally, and got CoverAlls to work on Travis. Leaving this issue open as a reminder to mock the HTTP calls.
