### ISSUE TITLE
Add SVG Worker

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#4]
Generate SVGs for various parameters:
  * Number of out-of-dates
  * Level of out-of-dates?

Use the same SVG for every gem which requires the same parameters (so we don't end up saving a large number of identical 'ok' badges, for instance)?

**Comment by bartkamphorst** [comment]
I was thinking about that as well, but then I also like the idea of just having one badge per project, which is a nice and clean association. We should for sure cache the existing badges and only generate a new one when appropriate.
