### ISSUE TITLE
Add language icons to info route

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#49]
Currently we just specify the name of the programming language a project uses like this:

<img width="319" alt="Screenshot 2020-10-07 at 16 54 29" src="https://user-images.githubusercontent.com/147111/95347965-cf9dd280-08bd-11eb-8a19-d9947c9f666c.png">

It might be nice to add instead, or in addition, a little language icon. There is [this](https://www.google.com/imgres?imgurl=https%3A%2F%2Fimg.favpng.com%2F13%2F1%2F21%2Fruby-web-development-programming-language-icon-png-favpng-juZNkNVLxBZQJxwkUPGNScZw2.jpg&imgrefurl=https%3A%2F%2Ffavpng.com%2Fpng_view%2Fprogramming-ruby-web-development-programming-language-icon-png%2FwcBiRAN2&tbnid=xLxLe7ZUREN80M&vet=12ahUKEwj73pLS3qLsAhUB2aQKHRlaD84QMygAegUIARC8AQ..i&docid=s3RF6FZOS6fqdM&w=820&h=819&q=ruby%20language%20icon&hl=en&ved=2ahUKEwj73pLS3qLsAhUB2aQKHRlaD84QMygAegUIARC8AQ), for instance, for Ruby. But there is also a ruby octicon.

We should experiment with this first before deciding whether it is really better than what we do currently. Anyone with a nice idea for how this could look is welcome to contribute a screenshot here!

**Comment by bartkamphorst** [comment]
What about https://devicon.dev/ ?
