### ISSUE TITLE
Accept Arrays of email addresses in `email:` and `MAIL_TO`

### ISSUE THREAD

**Issue by bartkamphorst** [repotag/cutting_edge#62]
Currently the `email:` key and `MAIL_TO` constant only accept single email address strings. However, sometimes it's useful to send these update mails to multiple recipients. So something like this would be nice:
```ruby
github:
  my_org:
    my_project:
      email: [a@example.com, b@example.com]
```

**Comment by dometto** [comment]
Turns out this already works!
