### ISSUE TITLE
Simple ERB Template for info route

### ISSUE THREAD

**Issue by dometto** [repotag/cutting_edge#7]
Use Bootstrap for layout, or is there something simpler/nicer?

**Comment by bartkamphorst** [comment]
Primer? 😉

**Comment by dometto** [comment]
Should include:

- [x] Name and language of the repo
- [x] Link to the repo on github/gitlab
- [x] The badge
- [x] Buttons for copying badge links (markdown, html?) to the clipboard
- [x] An overview of each file and its dependencies (table with different bg color for each status)
- [x] A clear statement that this overview was generated by cutting_edge, with a github link + star button for ourselves :)

**Comment by bartkamphorst** [comment]
> Buttons for copying badge links (markdown, html?) to the clipboard

I think we used [clipboard.js](https://clipboardjs.com/) in gollum for this.

**Comment by bartkamphorst** [comment]
Maybe also see whether Repotag is eligible for Github Sponsors?

**Comment by bartkamphorst** [comment]
The `info` route currently returns json. If we make the `info` route an html page, do we want another route to return the json (e.g., `/json`), or is there no need for this?

**Comment by dometto** [comment]
An additional `/json` or `/info/json` route would be nice, I think. It's cheap and easy, and perhaps some users would want to do some API scripting!

**Comment by bartkamphorst** [comment]
#37 ticks all the boxes! Awaiting final review. :)

**Comment by bartkamphorst** [comment]
Implemented in #37.
